#pragma once

#define MELONE_MOUSE_BUTTON_1         0
#define MELONE_MOUSE_BUTTON_2         1
#define MELONE_MOUSE_BUTTON_3         2
#define MELONE_MOUSE_BUTTON_4         3
#define MELONE_MOUSE_BUTTON_5         4
#define MELONE_MOUSE_BUTTON_6         5
#define MELONE_MOUSE_BUTTON_7         6
#define MELONE_MOUSE_BUTTON_8         7
#define MELONE_MOUSE_BUTTON_LAST      MELONE_MOUSE_BUTTON_8
#define MELONE_MOUSE_BUTTON_LEFT      MELONE_MOUSE_BUTTON_1
#define MELONE_MOUSE_BUTTON_RIGHT     MELONE_MOUSE_BUTTON_2
#define MELONE_MOUSE_BUTTON_MIDDLE    MELONE_MOUSE_BUTTON_3

